config/routes.rb
Sampaiodaveiga::Application.routes.draw do
  root 'patients#index'
  
  get 'log_in' => 'sessions#new', as: :log_in
  get 'log_out' => 'sessions#destroy', as: :log_out
  get 'sign_up' => 'users#new', as: :sign_up
  get 'patients/search' => 'patients#search'
  get 'patients/:id/legacy' => 'patients#legacy', as: :legacy_patient
  get 'patients/:id/first' => 'patients#first', as: :first_patient
  
  resources :patients do
    resources :diaries
  end
  resources :subsystems
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users, only: [ :new, :create ]
  

  

end

app/models/diary.rb
class Diary < ActiveRecord::Base
	belongs_to :patient

	validates :diagnostico, 
		presence: { message: "não pode ser nulo" }
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :diaries, dependent: :destroy
	belongs_to :subsystem

	validates :nome, 
		presence: { message: "não pode ser nulo" }
	validates :codigo_postal, 
		numericality: { allow_blank: true, message: "tem de ser numérico" }, 
		length: { is: 4, allow_nil: true, message: "só pode ter 4 números" }
	validates :codigo_postal_ext, 
		numericality: { allow_blank: true, message: "tem de ser numérico" }, 
		length: { is: 3, allow_nil: true, message: "só pode ter 3 números" }
	validates :rnu, 
		numericality: { allow_blank: true, message: "tem de ser numérico" }, 
		uniqueness: { allow_nil: true, message: "já existe" }
end

app/models/subsystem.rb
class Subsystem < ActiveRecord::Base
	has_many :patients

	validates :nome, 
		presence: { message: "não pode ser nulo"}, 
		uniqueness: { message: "já existe" }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :nome, 
		presence: { message: "não pode ser nulo" }, 
		length: { minimum: 3, message: "tem de ser mais de 3 caracteres" }
  validates :email, 
  		presence: { message: "não pode ser nulo" }, 
  		format: { with: VALID_EMAIL_REGEX, message: "é inválido" }, 
  		uniqueness: { case_sensitive: false, message: "é inválido" }
  validates :password, 
  		presence: { message: "não pode ser nulo" }, 
  		on: :create, 
  		length: { minimum: 5, message: "tem de ter mais de 5 caracteres" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private  
  
  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]  
  	end  
  
  	helper_method :current_user
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
	before_filter :load_patient

	def create
		@diary = @patient.diaries.create(diary_params)
		redirect_to patient_path(@patient)
	end

	def edit
		@diary = @patient.diaries.find(params[:id])
	end

	def update
		@diary = @patient.diaries.find(params[:id])

		if @diary.update_attributes(diary_params)
			redirect_to patient_path(@patient), notice: 'Diario atualizado'
		else
			render action: "edit"
		end
	end

	def destroy
		@diary = @patient.diaries.find(params[:id])
		@diary.destroy

		redirect_to patient_path(@patient), notice: 'Diário apagado'
	end

	private
		def load_patient
			@patient = Patient.find(params[:patient_id])
		end

		def diary_params
			params.require(:diary).permit(:diagnostico, :historial, :data_consulta)
		end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_filter :require_login

	def index
		@patients = Patient.paginate(page: params[:page]).order(:nome)
	end

	def show
		@patient = Patient.find(params[:id])
		@diaries = @patient.diaries.order('data_consulta')
		@patient.antecedentes_pessoais ||= "Não há registo"
		@patient.antecedentes_familiares ||= "Não há registo"
		@patient.historial ||= "Não há registo"
		@patient.diagnostico ||= "Não há registo"
	end

	def new
		@patient = Patient.new
		@patient.naturalidade ||= "Portuguesa"
		@patient.localidade ||= "Bragança"
		@patient.codigo_postal ||= 5300
	end

	def create
		@patient = Patient.new(patient_params)

		if @patient.save
			redirect_to @patient, notice: "Ficha criada!"
		else
			render :action => "new"
		end
	end

	def edit
		@patient = Patient.find(params[:id])
	end

	def legacy
		@patient = Patient.find(params[:id])
	end

	def first
		@patient = Patient.find(params[:id])
	end

	def update
		@patient = Patient.find(params[:id])

		if @patient.update_attributes(patient_params)
			redirect_to @patient, notice: "Ficha alterada!"
		else
			render :action => "edit"
		end
	end

	def destroy
		@patient = Patient.find(params[:id])
    	@patient.destroy

    	redirect_to patients_url, notice: 'Ficha eliminada!'
	end

	def search
		@patients = Patient.where("nome LIKE :prefix", prefix: "%#{params[:search_string]}%")
		#@patients = Patient.where("nome LIKE :prefix", prefix: "%#{params[:search_string].capitalize!}%")
	end

	private
	  	def require_login
	    	unless logged_in?
	      		redirect_to log_in_path
	    	end
	  	end

  		def logged_in?
    		!!current_user
  		end

  		def patient_params
  			params.require(:patient).permit(:nome, :data_de_nascimento, :naturalidade, :morada, :localidade, :codigo_postal, :codigo_postal_ext, :contacto, :rnu, :profissao, :servico_assistencial, :servico_assistencial_numero, :antecedentes_familiares, :antecedentes_pessoais, :historial, :diagnostico, :subsystem_id)
  		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:email])  
  		
  		if user && user.authenticate(params[:password]) && user.ativo
    		session[:user_id] = user.id  
    		redirect_to root_url, notice: "Bemvindo, #{user.nome}"  
  		else
  			flash.now[:error] = "Credenciais erradas"
  			render 'new'
  		end  
  	end

	def destroy
		session[:user_id] = nil
		redirect_to log_in_path, notice: 'Sessão terminada'
	end
end

app/controllers/subsystems_controller.rb
class SubsystemsController < ApplicationController
	before_filter :require_login

	def index
		@subsystems = Subsystem.all
	end

	def new
		@subsystem = Subsystem.new
	end

	def create
		@subsystem = Subsystem.new(subsystem_params)
		@subsystem.nome.upcase!

		if @subsystem.save
			redirect_to subsystems_path, notice: "Subsistema criado!"
		else
			render 'new'
		end
	end

	def edit
		@subsystem = Subsystem.find(params[:id])
	end

	def update
		@subsystem = Subsystem.find(params[:id])
		@subsystem.nome.upcase!

		if @subsystem.update_attributes(subsystem_params)
			redirect_to subsystems_path, notice: "Subsistema alterado!"
		else
			render :action => "edit"
		end
	end

	private
	  	def require_login
    		unless logged_in?
    	  		redirect_to log_in_path
    		end
  		end

  		def logged_in?
    		!!current_user
  		end

  		def subsystem_params
			params.require(:subsystem).permit(:nome)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "root", password: "toor"

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.email.downcase!
		@user.ativo = false

		if @user.save
			redirect_to log_in_path, notice: 'Utilizador registado com sucesso.'
		else
			render 'new'
		end
	end

	private
		def user_params
			params.require(:user).permit(:nome, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subsystems_helper.rb
module SubsystemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_new.html.erb
<%= form_for([@patient, @patient.diaries.build]) do |f| %>
	<%= f.submit 'Guardar nota', class: 'btn btn-success pull-right' %>
  	<fieldset>
  		<legend>Adicionar nota ao diário</legend>
		<div id="datetimepicker" class="input-append date">
        	<%= f.label :data_consulta, "Data da Consulta" %>
			<%= f.text_field :data_consulta %>
			<span class="add-on">
				<i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
			</span>
		</div>
  		<%= f.label :diagnostico, "Diagnóstico" %>
		<%= f.text_field :diagnostico %>
		<%= f.label :historial, "História Clínica" %>
		<%= f.text_area :historial %>
	</fieldset>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $('#datetimepicker').datetimepicker({
            format: 'yyyy-MM-dd',
            pickTime: false
        });
    });
</script>

app/views/diaries/_show.html.erb
<div class="accordion" id="accordion2">
    <% @diaries.each do |diary| %>
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=<%= "#" + diary.id.to_s %>>
                    <%= diary.data_consulta %> | <%= diary.diagnostico %>
                </a>
            </div>
            <div id=<%= diary.id %> class="accordion-body collapse">
                <div class="accordion-inner">
                    <dl>
                        <dt>História Clínica</dt>
                        <dd><%= diary.historial %></dd>
                        <%= link_to 'Apagar nota', [@patient,diary], method: :delete, data: { confirm: 'Tem a certeza?' }, class: 'btn btn-small btn-danger pull-right' %>
                        <%= link_to "Editar nota", edit_patient_diary_path(@patient, diary), class: 'btn btn-small pull-right' %>
                    </dl>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/diaries/edit.html.erb
<div class="row-fluid">
	<div class="span10 offset1">
		<h1><%= @diary.patient.nome %></h1>
		<h2><%= @diary.created_at.day %>/<%= @diary.created_at.month %>/<%= @diary.created_at.year %> | <%= @diary.diagnostico %></h2>

		<%= form_for([@patient,@diary]) do |f| %>
			<fieldset>
				<legend>Editar diário</legend>
				<div id="datetimepicker" class="input-append date">
        			<%= f.label :data_consulta, "Data da Consulta" %>
					<%= f.text_field :data_consulta %>
					<span class="add-on">
						<i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
					</span>
				</div>
				<%= f.label :diagnostico, "Diagnóstico" %>
				<%= f.text_field :diagnostico %>
				<%= f.label :historial, "História Clínica" %>
				<%= f.text_area :historial %>
			</fieldset>
			<%= f.submit 'Guardar', class: 'btn btn-success' %>
			<%= link_to 'Retroceder', patient_path(@patient), class: 'btn' %>
		<% end %>
	</div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#datetimepicker').datetimepicker({
            format: 'yyyy-MM-dd',
            pickTime: false
        });
    });
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<span>Sampaio da Veiga &copy; 2013</span>
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<% if current_user %>
				<div class="brand">
					Utilizador: <%= current_user.nome %>
				</div>
				<div class="nav-collapse collapse">
					<ul class="nav pull-right">
						<li><%= link_to "iMED", "http://www.imed.com.pt/imed/", target: "_blank" %></li>
						<li><%= link_to "Ver fichas", patients_path %></li>
						<li><%= link_to "Nova ficha", new_patient_path %></li>
						<li><%= link_to "Subsistemas", subsystems_path %></li>
						<li><%= link_to "Sair", log_out_path %></li>
					</ul>
				</div>
			<% end %>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sampaiodaveiga | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
		<%= yield %>
	</div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/patients/_error_messages.html.erb
<% if @patient.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            O formulário contém <%= pluralize(@patient.errors.count, "erro") %>.
        </div>
        <ul>
            <% @patient.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/patients/_firstform.html.erb
<%= form_for(@patient) do |f| %>
    <%= render 'error_messages' %>

    <fieldset>
        <legend>1ª consulta</legend>

        <label>Diagnóstico</label>
        <%= f.text_field :diagnostico %>
    
        <label>Historial</label>
        <%= f.text_area :historial %>
    </fieldset>
   	<%= f.submit 'Guardar' , class: 'btn btn-success' %>
    <%= link_to "Retroceder", patient_path, class: 'btn' %>
<% end %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
    <%= render 'error_messages' %>
    <div class="row-fluid">
        <div class="span6">
    
            <fieldset>
                <legend>Identificação</legend>
                <%= f.text_field :nome, placeholder: 'Nome' %>
                <div id="datetimepicker" class="input-append date">
                    <%= f.label :data_de_nascimento %>
                    <%= f.text_field :data_de_nascimento %>
                        <span class="add-on">
                            <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                        </span>
                </div>
                <%= f.text_field :naturalidade, placeholder: 'Naturalidade' %>
                <%= f.text_field :profissao, placeholder: 'Profissão' %>
                <%= f.text_field :contacto, placeholder: 'Telefone ou e-mail' %>
            </fieldset>
            
        </div>
        <div class="span6">
            <fieldset>
                <legend>Residência</legend>
                <%= f.text_field :morada, placeholder: 'Morada' %>
                <%= f.text_field :codigo_postal, class: 'span2' %>
                <%= f.text_field :codigo_postal_ext, class: 'span2' %>
                <%= f.text_field :localidade, placeholder: 'Localidade' %>
            </fieldset>
            <fieldset>
                <legend>Mais Dados</legend>
                <%= f.text_field :rnu, placeholder: 'RNU', class: 'span3' %><br />
                <%= f.collection_select :subsystem_id, Subsystem.all, :id, :nome, prompt: "Serviço Assistencial" %>
                <%= f.text_field :servico_assistencial_numero, placeholder: 'Subsistema', class: 'span3' %>
            </fieldset>
        </div>
    </div>
    <%= f.submit 'Guardar ficha', class: 'btn btn-success' %>
    <%= link_to 'Cancelar', patients_path, class: 'btn' %>          
<% end %>

app/views/patients/_legacyform.html.erb
<%= form_for(@patient) do |f| %>
    <%= render 'error_messages' %>

    <fieldset>
        <legend>Antecedentes</legend>
        
        <label>Familiares</label>
        <%= f.text_area :antecedentes_familiares %>
        <label>Pessoais</label>
        <%= f.text_area :antecedentes_pessoais %>
    </fieldset>
    <%= f.submit 'Guardar', class: 'btn btn-success' %>
    <%= link_to "Retroceder", patient_path, class: 'btn' %>
<% end %>

app/views/patients/_patientantecedentes.html.erb
<dl>
	<dt>Antecedentes Familiares</dt>
	<dd><%= @patient.antecedentes_familiares %></dd>
	<dt>Antecedentes Pessoais</dt>
	<dd><%= @patient.antecedentes_pessoais %></dd>
	<%= link_to "Editar", legacy_patient_path, class:'btn btn-small pull-right' %>
</dl>

app/views/patients/_patientid.html.erb
<legend>Identificação</legend>
<dl>
	<dt>Data de nascimento</dt>
	<dd><%= @patient.data_de_nascimento %></dd>
			
	<dt>Idade:</dt> 
	<% unless @patient.data_de_nascimento.nil? %>
		<dd><%= distance_of_time_in_words_to_now(@patient.data_de_nascimento) %></dd>
	<% else %>
		<dd></dd>
	<% end %>
			
	<dt>Naturalidade</dt> 
	<dd><%= @patient.naturalidade %></dd>
				
	<dt>N. Utente</dt> 
	<dd><%= @patient.rnu %></dd>
				
	<dt>Profissão</dt> 
	<dd><%= @patient.profissao %></dd>
				
	<dt>Sub-sistema</dt>
	<dd>
		<% unless @patient.subsystem.nil? %>
			<%= @patient.subsystem.nome %>-
			<%= @patient.servico_assistencial_numero %>
		<% else %>
			<%= @patient.servico_assistencial %>-
			<%= @patient.servico_assistencial_numero %>
		<% end %>
	</dd>
				
	<dt>Morada</dt>
	<dd><%= @patient.morada %></dd>
			
	<dt>C. postal</dt> 
	<dd><%= @patient.codigo_postal %>-<%= @patient.codigo_postal_ext %></dd>
			
	<dt>Localidade</dt> 
	<dd><%= @patient.localidade %></dd>
				
	<dt>Contacto</dt> 
	<dd><%= @patient.contacto %></dd>
</dl>

app/views/patients/_search.html.erb
<div class="form-search">
	<%= form_tag("patients/search", :method => "get") do %>
		<div class="input-append">
			<%= text_field_tag 'search_string', nil, placeholder: 'Pesquisar...', class: 'span2 search-query' %>
			<%= submit_tag '?', class: 'btn' %>
		</div>
	<% end %>
</div>

app/views/patients/edit.html.erb
<% provide(:title, 'Editar Ficha') %>
<h1>Editar ficha</h1>

<div class="row-fluid">
    <div class="span10 offset1">
		<%= render 'form' %>
	</div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#datetimepicker').datetimepicker({
            format: 'yyyy-MM-dd',
            pickTime: false
        });
    });
</script>

app/views/patients/first.html.erb
<% provide(:title, @patient.nome ) %>

<h1><%= @patient.nome %></h1>

<div class="row-fluid">
    <div class="span10 offset1">
		<%= render 'firstform' %>
	</div>
</div>

app/views/patients/index.html.erb
<% provide(:title, 'Fichas') %>

<%= render 'search' %>

<h1>Fichas individuais</h1>

<%= will_paginate %>

<table class="table">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Idade</th>
			<th>Ultima Consulta</th>
			<th>Ultimo Diagnóstico</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @patients.each do |patient| %>
			<tr>
				<td><%= link_to patient.nome, patient %></td>
				<% unless patient.data_de_nascimento.nil? %>
					<td><%= distance_of_time_in_words_to_now(patient.data_de_nascimento) %></td>
				<% else %>
					<td></td>
				<% end %>
				<% unless patient.diaries.empty? %>
					<td>
						<%= patient.diaries.last.created_at.day %>/
						<%= patient.diaries.last.created_at.month %>/
						<%= patient.diaries.last.created_at.year %>
					</td>
					<td><%= patient.diaries.last.diagnostico %></td>
				<% else %>
					<td></td>
					<td></td>
				<% end %>
				<td><%= link_to "Editar", patient %></td>
			</tr>
		<% end %>
	<tbody>
</table>

<%= will_paginate %>

app/views/patients/legacy.html.erb
<% provide(:title, @patient.nome ) %>

<h1><%= @patient.nome %></h1>

<div class="row-fluid">
    <div class="span10 offset1">
		<%= render 'legacyform' %>
	</div>
</div>

app/views/patients/new.html.erb
<% provide(:title, "Nova ficha") %>
<h1>Nova ficha</h1>

<div class="row-fluid">
	<div class="span12">
		<%= render 'form' %>
	</div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#datetimepicker').datetimepicker({
            format: 'yyyy-MM-dd',
            pickTime: false
        });
    });
</script>

app/views/patients/search.html.erb
<% provide(:title, 'Pesquisa') %>
<h1>Resultados da pesquisa</h1>

<% if @patients.empty? %>
	<h2>Sem resultados</h2>
<% else %>
	<table class="table">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Idade</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @patients.each do |patient| %>
				<tr>
					<td><%= link_to patient.nome, patient %></td>
					<% unless patient.data_de_nascimento.nil? %>
						<td><%= distance_of_time_in_words_to_now(patient.data_de_nascimento) %></td>
					<% else %>
						<td></td>
					<% end %>
					<td><%= link_to "Ver", patient %></td>
				</tr>
			<% end %>
		<tbody>
	</table>
<% end %>

app/views/patients/show.html.erb
<% provide(:title, @patient.nome) %>

<h1><%= @patient.nome %></h1>

<div class="row-fluid">
	<div class="span3 well well-small">
		<%= render 'patientid' %>

		<%= link_to "Editar", edit_patient_path, class: 'btn' %>
		<%= link_to "Eliminar", @patient, confirm: 'Eliminar ficha?', method: :delete, class: 'btn btn-danger' %>
	</div>
	<div class="span9 well well-small tabs">
		<ul class="nav nav-tabs">
			<li><a href="#tabs-1" data-target="#tabs-1" data-toggle="tab">Antecedentes</a></li>
			<li><a href="#tabs-2" data-target="#tabs-2" data-toggle="tab">1ª Consulta</a></li>
			<li class="active"><a href="#tabs-3" data-target="#tabs-3" data-toggle="tab">Diário Clínico</a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane" id="tabs-1">
				<%= render 'patientantecedentes' %>
			</div>
			<div class="tab-pane" id="tabs-2">
  				<%= render 'firstappointment' %>
  			</div>
  			<div class="tab-pane active fade in" id="tabs-3">
  				<%= render 'diaries/show' %>
  				<div class="span11">
  					<%= render 'diaries/new' %>
				</div>
  			</div>
  		</div>
	</div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#datetimepicker').datetimepicker({
            format: 'yyyy-MM-dd',
            pickTime: false
        });
    });
</script>

app/views/subsystems/_error_messages.html.erb
<% if @subsystem.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            O formulário contém <%= pluralize(@subsystem.errors.count, "erro") %>.
        </div>
        <ul>
            <% @subsystem.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/subsystems/_form.html.erb
<%= form_for(@subsystem) do |f| %>
	<%= render 'error_messages' %>

	<fieldset>
		<%= f.text_field :nome, placeholder: 'Nome' %>
	</fieldset>
	<%= f.submit "Guardar" %>
<% end %>

app/views/subsystems/edit.html.erb
<% provide(:title, "Editar Sub-sistema") %>
<h1>Editar <%= @subsystem.nome %></h1>

<div class="row-fluid">
	<div class="span12">
		<%= render 'form' %>
	</div>
</div>

app/views/subsystems/index.html.erb
<% provide(:title, "Sub-sistemas") %>
<h1>Sub-Sistemas</h1>

<div class="row-fluid">
	<div class="span4 offset4">
		<table class="table">
			<thead>
				<th>
					<td></td>
				</th>
			</thead>
			<tbody>
				<% @subsystems.each do |subsystem| %>
					<tr>
						<td><%= link_to subsystem.nome, edit_subsystem_path(subsystem) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<%= link_to "novo", new_subsystem_path, class: 'btn btn-success pull-right' %>
	</div>
</div>

app/views/subsystems/new.html.erb
<h1>Novo Sub-sistema</h1>

<div class="row-fluid">
	<div class="span12">
		<%= render 'form' %>
	</div>
</div>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registo</h1>

<div class="row-fluid">
    <div class="span6 offset3">
        <%= form_for @user do |f| %>  
            <%= render 'error_messages' %>
            <div class="field">  
                <%= f.label :nome %>  
                <%= f.text_field :nome %>  
            </div>
            <div class="field">  
                <%= f.label :email %>  
                <%= f.text_field :email %>  
            </div>  
            <div class="field">  
                <%= f.label :password, 'Senha' %>  
                <%= f.password_field :password %>  
            </div>  
            <div class="field">  
                <%= f.label :password_confirmation, 'Confirmação da senha' %>  
                <%= f.password_field :password_confirmation %>  
            </div>  
            <div class="actions">
                <%= f.submit 'Submeter', class: 'btn btn-primary btn-large'%>
            </div>  
        <% end %>
    </div>
</div>